"""Initial migration with User and Contact models

Revision ID: a4dba201ae77
Revises: 
Create Date: 2025-03-31 15:32:46.386734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4dba201ae77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('theme', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('company', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_middle_name'), ['middle_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_phone_number'), ['phone_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_phone_number'))
        batch_op.drop_index(batch_op.f('ix_contacts_middle_name'))
        batch_op.drop_index(batch_op.f('ix_contacts_last_name'))
        batch_op.drop_index(batch_op.f('ix_contacts_first_name'))
        batch_op.drop_index(batch_op.f('ix_contacts_email'))

    op.drop_table('contacts')
    op.drop_table('users')
    # ### end Alembic commands ###
